/**
 * JOM STUDIO — Commerce & Ops Config (single source of truth)
 * Products support i18n: { en, es, fr, pt } blocks under `.i18n`
 * UI language: localStorage `jom_lang` (shared with index.html)
 */
(function (global) {
  function L(en, es, fr, pt) {
    return { en, es, fr: fr || en, pt: pt || es || en };
  }
  function pack(en, es, fr, pt) {
    return {
      en: en,
      es: es || en,
      fr: fr || en,
      pt: pt || es || en,
    };
  }

  const CONFIG = {
    brand: {
      name: "JOM STUDIO",
      tagline: "DIGITAL ALCHEMY",
      siteUrl: "https://jomstudiovzla.github.io/Jomstudiopage",
      timezone: "America/Caracas",
    },

    contact: {
      whatsapp: "584165159067",
      email: "jomstudiovzla@gmail.com",
      formspreeEndpoint: "",
      notifyWebhook: "",
    },

    crypto: {
      network: "TRC20",
      asset: "USDT",
      address: "TLnHhj8595k5Fg1jFvgB7Med7iCbGdmTMN",
      usdtContract: "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
      trongridBase: "https://api.trongrid.io",
      trongridApiKey: "",
      amountToleranceUsdt: 0.5,
      lookbackHours: 72,
      minConfirmations: 1,
    },

    /**
     * Category order for pricing page
     */
    categoryOrder: [
      "web",
      "gamification",
      "branding",
      "ai",
      "photo",
      "ugc",
      "automation",
    ],

    products: {
      /* ───────────── WEB ───────────── */
      spark: {
        id: "spark",
        sku: "JOM-WEB-SPARK-200",
        priceUsdt: 200,
        currency: "USDT",
        network: "TRC20",
        category: "web",
        type: "solo",
        protocol: "PROTOCOL_02",
        badgeKey: "badge_entry",
        featured: true,
        i18n: {
          en: {
            name: "Micro Alchemy Spark",
            headline: "Conversion landing + premium motion",
            description: "One-page landing with sales copy structure, social proof, WhatsApp CTA and GSAP motion. Built to capture leads fast.",
            eta: "3–5 business days",
            deliverables: ["Responsive 1-page landing", "Hero + offer + proof + CTA", "GSAP entrance/scroll motion", "WhatsApp CTA prefilled", "Deploy or ZIP", "1 revision round"],
            notIncluded: ["Paid domain", "Multi-page CMS", "Backend"],
          },
          es: {
            name: "Micro Alchemy Spark",
            headline: "Landing de conversión + animaciones premium",
            description: "Landing de una página con estructura de venta, prueba social, CTA WhatsApp y motion GSAP. Lista para captar leads.",
            eta: "3–5 días hábiles",
            deliverables: ["Landing responsive 1 página", "Hero + oferta + prueba + CTA", "Animaciones GSAP", "CTA WhatsApp prearmado", "Deploy o ZIP", "1 ronda de revisiones"],
            notIncluded: ["Dominio pago", "CMS multi-página", "Backend"],
          },
          fr: {
            name: "Micro Alchemy Spark",
            headline: "Landing de conversion + motion premium",
            description: "Landing one-page avec structure de vente, preuve sociale, CTA WhatsApp et motion GSAP.",
            eta: "3–5 jours ouvrés",
            deliverables: ["Landing responsive 1 page", "Hero + offre + preuve + CTA", "Motion GSAP", "CTA WhatsApp", "Deploy ou ZIP", "1 round de revisions"],
            notIncluded: ["Domaine payant", "CMS multi-pages", "Backend"],
          },
          pt: {
            name: "Micro Alchemy Spark",
            headline: "Landing de conversão + motion premium",
            description: "Landing de uma página com estrutura de venda, prova social, CTA WhatsApp e motion GSAP.",
            eta: "3–5 dias úteis",
            deliverables: ["Landing responsive 1 página", "Hero + oferta + prova + CTA", "Motion GSAP", "CTA WhatsApp", "Deploy ou ZIP", "1 rodada de revisões"],
            notIncluded: ["Domínio pago", "CMS multi-página", "Backend"],
          },
        },
      },
      launch: {
        id: "launch",
        sku: "JOM-WEB-LAUNCH-300",
        priceUsdt: 300,
        currency: "USDT",
        network: "TRC20",
        category: "web",
        type: "solo",
        protocol: "PROTOCOL_02",
        badgeKey: "badge_best",
        featured: true,
        i18n: {
          en: {
            name: "Digital Alchemy Launch Kit",
            headline: "Interactive web: 3D/WebGL + custom cursor + GSAP",
            description: "Immersive site layer: light Three.js/WebGL hero, custom cursor, GSAP timelines, studio-grade dark UI.",
            eta: "5–7 business days",
            deliverables: ["Three.js or Canvas hero", "Custom cursor + mobile fallback", "GSAP timelines", "Premium dark UI", "Perf pass", "Deploy/ZIP + README", "2 revision rounds"],
            notIncluded: ["Full e-commerce", "Native app", "3-month SEO retainer"],
          },
          es: {
            name: "Digital Alchemy Launch Kit",
            headline: "Web interactiva 3D + cursor custom + GSAP",
            description: "Capa inmersiva: hero Three.js/WebGL ligero, cursor custom, timelines GSAP y UI dark studio-grade.",
            eta: "5–7 días hábiles",
            deliverables: ["Hero Three.js o Canvas", "Cursor custom + fallback mobile", "Timelines GSAP", "UI dark premium", "Pass de performance", "Deploy/ZIP + README", "2 rondas de revisiones"],
            notIncluded: ["E-commerce completo", "App nativa", "SEO 3 meses"],
          },
          fr: {
            name: "Digital Alchemy Launch Kit",
            headline: "Web interactif 3D + curseur custom + GSAP",
            description: "Couche immersive : hero Three.js/WebGL léger, curseur custom, timelines GSAP, UI dark studio.",
            eta: "5–7 jours ouvrés",
            deliverables: ["Hero Three.js ou Canvas", "Curseur custom", "Timelines GSAP", "UI dark premium", "Perf pass", "Deploy/ZIP", "2 rounds de revisions"],
            notIncluded: ["E-commerce complet", "App native", "SEO 3 mois"],
          },
          pt: {
            name: "Digital Alchemy Launch Kit",
            headline: "Web interativa 3D + cursor custom + GSAP",
            description: "Camada imersiva: hero Three.js/WebGL leve, cursor custom, timelines GSAP e UI dark studio.",
            eta: "5–7 dias úteis",
            deliverables: ["Hero Three.js ou Canvas", "Cursor custom", "Timelines GSAP", "UI dark premium", "Pass de performance", "Deploy/ZIP", "2 rodadas de revisões"],
            notIncluded: ["E-commerce completo", "App nativa", "SEO 3 meses"],
          },
        },
      },
      web_ecommerce: {
        id: "web_ecommerce",
        sku: "JOM-WEB-SHOP-450",
        priceUsdt: 450,
        currency: "USDT",
        network: "TRC20",
        category: "web",
        type: "solo",
        protocol: "PROTOCOL_02",
        badgeKey: "badge_pro",
        i18n: {
          en: {
            name: "Commerce Storefront",
            headline: "Fast e-commerce front + cart flow",
            description: "Responsive storefront with catalog, product detail, cart UX and checkout handoff (WhatsApp or payment link).",
            eta: "8–12 business days",
            deliverables: ["Catalog + product pages", "Cart UX", "Checkout handoff", "Mobile-first UI", "Deploy", "2 revision rounds"],
            notIncluded: ["Payment gateway legal setup", "Inventory ERP"],
          },
          es: {
            name: "Tienda E-commerce",
            headline: "Storefront rápido + flujo de carrito",
            description: "Tienda responsive con catálogo, ficha, carrito y cierre por WhatsApp o link de pago.",
            eta: "8–12 días hábiles",
            deliverables: ["Catálogo + fichas", "UX de carrito", "Cierre de compra", "UI mobile-first", "Deploy", "2 rondas"],
            notIncluded: ["Pasarela legal completa", "ERP de inventario"],
          },
          fr: {
            name: "Boutique E-commerce",
            headline: "Vitrine rapide + panier",
            description: "Boutique responsive : catalogue, fiche produit, panier et clôture WhatsApp / lien de paiement.",
            eta: "8–12 jours ouvrés",
            deliverables: ["Catalogue + fiches", "UX panier", "Checkout handoff", "UI mobile", "Deploy", "2 rounds"],
            notIncluded: ["Setup légal PSP", "ERP stock"],
          },
          pt: {
            name: "Loja E-commerce",
            headline: "Vitrine rápida + fluxo de carrinho",
            description: "Loja responsive com catálogo, ficha, carrinho e fechamento WhatsApp ou link de pagamento.",
            eta: "8–12 dias úteis",
            deliverables: ["Catálogo + fichas", "UX carrinho", "Checkout handoff", "UI mobile", "Deploy", "2 rodadas"],
            notIncluded: ["Setup legal de gateway", "ERP de estoque"],
          },
        },
      },
      web_fullstack: {
        id: "web_fullstack",
        sku: "JOM-WEB-FS-700",
        priceUsdt: 700,
        currency: "USDT",
        network: "TRC20",
        category: "web",
        type: "solo",
        protocol: "PROTOCOL_02",
        badgeKey: "badge_premium",
        i18n: {
          en: {
            name: "Full-Stack Portal",
            headline: "Next.js / Node portal with real data layer",
            description: "Custom portal (bookings, listings, dashboards) with API + database architecture.",
            eta: "14–21 business days",
            deliverables: ["Architecture map", "Next.js UI", "API endpoints", "DB schema", "Auth basic", "Deploy docs", "2 revision rounds"],
            notIncluded: ["Ongoing DevOps retainer", "App Store publish"],
          },
          es: {
            name: "Portal Full-Stack",
            headline: "Portal Next.js / Node con capa de datos real",
            description: "Portal a medida (reservas, listados, dashboards) con API + base de datos.",
            eta: "14–21 días hábiles",
            deliverables: ["Mapa de arquitectura", "UI Next.js", "Endpoints API", "Esquema DB", "Auth básica", "Docs deploy", "2 rondas"],
            notIncluded: ["Retainer DevOps", "Publicación App Store"],
          },
          fr: {
            name: "Portail Full-Stack",
            headline: "Portail Next.js / Node avec data layer",
            description: "Portail sur mesure (réservations, listings, dashboards) avec API + base de données.",
            eta: "14–21 jours ouvrés",
            deliverables: ["Architecture", "UI Next.js", "API", "Schéma DB", "Auth basique", "Docs deploy", "2 rounds"],
            notIncluded: ["Retainer DevOps", "Publication store"],
          },
          pt: {
            name: "Portal Full-Stack",
            headline: "Portal Next.js / Node com data layer",
            description: "Portal sob medida (reservas, listagens, dashboards) com API + banco de dados.",
            eta: "14–21 dias úteis",
            deliverables: ["Arquitetura", "UI Next.js", "API", "Schema DB", "Auth básica", "Docs deploy", "2 rodadas"],
            notIncluded: ["Retainer DevOps", "Publicação store"],
          },
        },
      },

      /* ───────────── GAMIFICATION ───────────── */
      engine: {
        id: "engine",
        sku: "JOM-GAME-ENGINE-600",
        priceUsdt: 600,
        currency: "USDT",
        network: "TRC20",
        category: "gamification",
        type: "solo",
        protocol: "PROTOCOL_01",
        badgeKey: "badge_pro",
        featured: true,
        i18n: {
          en: {
            name: "Interactive Engine Build",
            headline: "Custom mini-game / web interactive engine",
            description: "Playable web engine (Canvas/WebGL): mechanics, UI feedback, deployable build.",
            eta: "10–14 business days",
            deliverables: ["1-page GDD", "Playable prototype", "UI feedback", "Web deploy", "Handoff doc", "2 revision rounds"],
            notIncluded: ["Mainnet blockchain prod", "Ads budget", "Unlimited 24/7 support"],
          },
          es: {
            name: "Motor Interactivo",
            headline: "Mini-juego / motor interactivo a medida",
            description: "Motor web jugable (Canvas/WebGL): mecánicas, UI y build deployable.",
            eta: "10–14 días hábiles",
            deliverables: ["GDD 1 página", "Prototipo jugable", "UI feedback", "Deploy web", "Handoff", "2 rondas"],
            notIncluded: ["Blockchain mainnet prod", "Budget de ads", "Soporte 24/7 ilimitado"],
          },
          fr: {
            name: "Moteur Interactif",
            headline: "Mini-jeu / moteur interactif sur mesure",
            description: "Moteur web jouable (Canvas/WebGL) : mécaniques, UI, build déployable.",
            eta: "10–14 jours ouvrés",
            deliverables: ["GDD 1 page", "Prototype jouable", "UI feedback", "Deploy web", "Handoff", "2 rounds"],
            notIncluded: ["Blockchain mainnet", "Budget ads", "Support 24/7"],
          },
          pt: {
            name: "Motor Interativo",
            headline: "Mini-jogo / motor interativo sob medida",
            description: "Motor web jogável (Canvas/WebGL): mecânicas, UI e build deployável.",
            eta: "10–14 dias úteis",
            deliverables: ["GDD 1 página", "Protótipo jogável", "UI feedback", "Deploy web", "Handoff", "2 rodadas"],
            notIncluded: ["Blockchain mainnet", "Budget de ads", "Suporte 24/7"],
          },
        },
      },
      game_cards: {
        id: "game_cards",
        sku: "JOM-GAME-CARDS-800",
        priceUsdt: 800,
        currency: "USDT",
        network: "TRC20",
        category: "gamification",
        type: "solo",
        protocol: "PROTOCOL_01",
        badgeKey: "badge_premium",
        i18n: {
          en: {
            name: "Card / Tactical Web Game",
            headline: "Full card-game interaction layer",
            description: "Turn-based or tactical card game loop on web (inspired by portfolio engines like Crypto Water War).",
            eta: "16–22 business days",
            deliverables: ["Core loop design", "Card UI system", "Combat/turn logic", "Balance pass v1", "Web build", "2 revision rounds"],
            notIncluded: ["100+ original illustrations (use Art Pack)", "Live ops seasons"],
          },
          es: {
            name: "Juego de Cartas / Táctico Web",
            headline: "Capa completa de interacción de cartas",
            description: "Loop de cartas por turnos o táctico en web (estilo motores del portfolio).",
            eta: "16–22 días hábiles",
            deliverables: ["Diseño de core loop", "Sistema UI de cartas", "Lógica de turnos", "Balance v1", "Build web", "2 rondas"],
            notIncluded: ["100+ ilustraciones originales (ver Art Pack)", "Live ops"],
          },
          fr: {
            name: "Jeu de Cartes / Tactique Web",
            headline: "Couche d'interaction cartes complète",
            description: "Boucle de cartes tour par tour ou tactique sur le web.",
            eta: "16–22 jours ouvrés",
            deliverables: ["Core loop", "UI cartes", "Logique de tours", "Balance v1", "Build web", "2 rounds"],
            notIncluded: ["100+ illustrations originales", "Live ops"],
          },
          pt: {
            name: "Jogo de Cartas / Tático Web",
            headline: "Camada completa de interação de cartas",
            description: "Loop de cartas por turnos ou tático na web.",
            eta: "16–22 dias úteis",
            deliverables: ["Core loop", "UI de cartas", "Lógica de turnos", "Balance v1", "Build web", "2 rodadas"],
            notIncluded: ["100+ ilustrações originais", "Live ops"],
          },
        },
      },

      /* ───────────── BRANDING ───────────── */
      brand_identity: {
        id: "brand_identity",
        sku: "JOM-BRAND-ID-250",
        priceUsdt: 250,
        currency: "USDT",
        network: "TRC20",
        category: "branding",
        type: "solo",
        protocol: "PROTOCOL_06",
        badgeKey: "badge_fast",
        i18n: {
          en: {
            name: "Brand Identity Kit",
            headline: "Logo system + palette + type + usage rules",
            description: "Compact brand system ready for web and social: marks, colors, type, do/don't.",
            eta: "5–8 business days",
            deliverables: ["Primary + alt marks", "Color + type system", "Basic brand PDF", "Social avatar set", "1 revision round"],
            notIncluded: ["Full print stationery suite", "Trademark legal filing"],
          },
          es: {
            name: "Kit de Identidad de Marca",
            headline: "Logo + paleta + tipografía + reglas de uso",
            description: "Sistema de marca compacto listo para web y redes: marcas, color, tipo, usos.",
            eta: "5–8 días hábiles",
            deliverables: ["Marca principal + alts", "Color + tipo", "PDF de marca básico", "Set de avatar social", "1 ronda"],
            notIncluded: ["Papelería impresa completa", "Registro legal de marca"],
          },
          fr: {
            name: "Kit d'Identité de Marque",
            headline: "Logo + palette + typo + règles",
            description: "Système de marque compact pour web et social.",
            eta: "5–8 jours ouvrés",
            deliverables: ["Marques primaire + alt", "Couleur + typo", "PDF marque", "Avatars social", "1 round"],
            notIncluded: ["Papeterie complète", "Dépôt légal"],
          },
          pt: {
            name: "Kit de Identidade de Marca",
            headline: "Logo + paleta + tipo + regras",
            description: "Sistema de marca compacto para web e redes.",
            eta: "5–8 dias úteis",
            deliverables: ["Marca principal + alts", "Cor + tipo", "PDF de marca", "Avatares social", "1 rodada"],
            notIncluded: ["Papelaria completa", "Registro legal"],
          },
        },
      },
      brand_packaging: {
        id: "brand_packaging",
        sku: "JOM-BRAND-PACK-350",
        priceUsdt: 350,
        currency: "USDT",
        network: "TRC20",
        category: "branding",
        type: "solo",
        protocol: "PROTOCOL_06",
        badgeKey: "badge_pro",
        i18n: {
          en: {
            name: "Packaging Dielines Pack",
            headline: "Structural packaging vectors (mailer, doypack, bags)",
            description: "Production-ready dielines and artboards for physical packaging.",
            eta: "7–10 business days",
            deliverables: ["2–3 dieline structures", "Print-ready vectors", "Mockup previews", "1 revision round"],
            notIncluded: ["Industrial print production", "Shipping of samples"],
          },
          es: {
            name: "Pack de Troqueles / Packaging",
            headline: "Troqueles estructurales (mailer, doypack, bolsas)",
            description: "Dielines listos para producción y artboards de empaque físico.",
            eta: "7–10 días hábiles",
            deliverables: ["2–3 estructuras de troquel", "Vectores print-ready", "Mockups", "1 ronda"],
            notIncluded: ["Producción industrial", "Envío de samples"],
          },
          fr: {
            name: "Pack Gabarits Packaging",
            headline: "Gabarits structurels (mailer, doypack, sacs)",
            description: "Dielines prêts pour production d'emballage physique.",
            eta: "7–10 jours ouvrés",
            deliverables: ["2–3 structures", "Vecteurs print-ready", "Mockups", "1 round"],
            notIncluded: ["Production industrielle", "Envoi d'échantillons"],
          },
          pt: {
            name: "Pack de Troquéis / Packaging",
            headline: "Troquéis estruturais (mailer, doypack, sacolas)",
            description: "Dielines prontos para produção de embalagem física.",
            eta: "7–10 dias úteis",
            deliverables: ["2–3 estruturas", "Vetores print-ready", "Mockups", "1 rodada"],
            notIncluded: ["Produção industrial", "Envio de samples"],
          },
        },
      },

      /* ───────────── AI ART ───────────── */
      ai_visual: {
        id: "ai_visual",
        sku: "JOM-AI-VISUAL-200",
        priceUsdt: 200,
        currency: "USDT",
        network: "TRC20",
        category: "ai",
        type: "solo",
        protocol: "PROTOCOL_03",
        badgeKey: "badge_entry",
        i18n: {
          en: {
            name: "AI Visual Direction Pack",
            headline: "12–20 curated AI visuals + prompt system",
            description: "Art direction with Midjourney/Kling pipeline, selection and light retouch for brand use.",
            eta: "3–6 business days",
            deliverables: ["Moodboard", "12–20 finals", "Prompt library", "Usage notes", "1 revision round"],
            notIncluded: ["Unlimited gens", "Video full production (see UGC)"],
          },
          es: {
            name: "Pack Dirección Visual IA",
            headline: "12–20 visuales IA curados + sistema de prompts",
            description: "Dirección de arte con pipeline Midjourney/Kling, selección y retoque ligero.",
            eta: "3–6 días hábiles",
            deliverables: ["Moodboard", "12–20 finales", "Librería de prompts", "Notas de uso", "1 ronda"],
            notIncluded: ["Generaciones ilimitadas", "Video full (ver UGC)"],
          },
          fr: {
            name: "Pack Direction Visuelle IA",
            headline: "12–20 visuels IA + système de prompts",
            description: "Direction artistique pipeline Midjourney/Kling, sélection et retouche légère.",
            eta: "3–6 jours ouvrés",
            deliverables: ["Moodboard", "12–20 finaux", "Lib de prompts", "Notes d'usage", "1 round"],
            notIncluded: ["Gens illimitées", "Vidéo full (voir UGC)"],
          },
          pt: {
            name: "Pack Direção Visual IA",
            headline: "12–20 visuais IA + sistema de prompts",
            description: "Direção de arte com pipeline Midjourney/Kling, seleção e retoque leve.",
            eta: "3–6 dias úteis",
            deliverables: ["Moodboard", "12–20 finais", "Lib de prompts", "Notas de uso", "1 rodada"],
            notIncluded: ["Gerações ilimitadas", "Vídeo full (ver UGC)"],
          },
        },
      },
      art_game: {
        id: "art_game",
        sku: "JOM-AI-GAMEART-320",
        priceUsdt: 320,
        currency: "USDT",
        network: "TRC20",
        category: "ai",
        type: "solo",
        protocol: "PROTOCOL_03",
        badgeKey: "badge_pro",
        i18n: {
          en: {
            name: "Game Illustration Pack",
            headline: "Character/card art set for interactive projects",
            description: "Cohesive illustration set for games or card UIs (characters, icons, key art).",
            eta: "6–10 business days",
            deliverables: ["Style frame", "8–15 assets", "Transparent exports", "Naming convention", "1 revision round"],
            notIncluded: ["Full 100+ card library", "3D modeling"],
          },
          es: {
            name: "Pack Ilustración para Juegos",
            headline: "Arte de personajes/cartas para proyectos interactivos",
            description: "Set cohesivo para juegos o UIs de cartas (personajes, iconos, key art).",
            eta: "6–10 días hábiles",
            deliverables: ["Style frame", "8–15 assets", "Exports transparentes", "Convención de nombres", "1 ronda"],
            notIncluded: ["Librería 100+ cartas", "Modelado 3D"],
          },
          fr: {
            name: "Pack Illustration Jeu",
            headline: "Art personnages/cartes pour projets interactifs",
            description: "Set cohérent pour jeux ou UI de cartes.",
            eta: "6–10 jours ouvrés",
            deliverables: ["Style frame", "8–15 assets", "Exports", "Naming", "1 round"],
            notIncluded: ["Lib 100+ cartes", "Modélisation 3D"],
          },
          pt: {
            name: "Pack Ilustração para Jogos",
            headline: "Arte de personagens/cartas para projetos interativos",
            description: "Set coeso para jogos ou UIs de cartas.",
            eta: "6–10 dias úteis",
            deliverables: ["Style frame", "8–15 assets", "Exports", "Naming", "1 rodada"],
            notIncluded: ["Lib 100+ cartas", "Modelagem 3D"],
          },
        },
      },

      /* ───────────── PHOTO ───────────── */
      photo_session: {
        id: "photo_session",
        sku: "JOM-PHOTO-SESSION-220",
        priceUsdt: 220,
        currency: "USDT",
        network: "TRC20",
        category: "photo",
        type: "solo",
        protocol: "PROTOCOL_05",
        badgeKey: "badge_fast",
        i18n: {
          en: {
            name: "Brand Photo Session",
            headline: "Directed photo session for brand / founder",
            description: "On-location or studio-style direction session + curated selects and color grade.",
            eta: "Scheduling + 4–7 days delivery",
            deliverables: ["1 session (up to 2h)", "20–40 edited selects", "Color grade", "Web-ready exports"],
            notIncluded: ["Travel outside agreed zone", "Video production", "Prints"],
          },
          es: {
            name: "Sesión de Foto de Marca",
            headline: "Sesión dirigida para marca / founder",
            description: "Sesión en locación o estilo estudio + selección curada y color grade.",
            eta: "Agenda + 4–7 días de entrega",
            deliverables: ["1 sesión (hasta 2h)", "20–40 selects editados", "Color grade", "Exports web"],
            notIncluded: ["Viajes fuera de zona", "Producción de video", "Impresiones"],
          },
          fr: {
            name: "Séance Photo de Marque",
            headline: "Séance dirigée marque / fondateur",
            description: "Séance sur site ou style studio + selects et étalonnage.",
            eta: "Planning + 4–7 jours livraison",
            deliverables: ["1 séance (jusqu'à 2h)", "20–40 selects", "Étalonnage", "Exports web"],
            notIncluded: ["Déplacements hors zone", "Vidéo", "Tirages"],
          },
          pt: {
            name: "Sessão de Foto de Marca",
            headline: "Sessão dirigida para marca / founder",
            description: "Sessão em locação ou estilo estúdio + selects e color grade.",
            eta: "Agenda + 4–7 dias de entrega",
            deliverables: ["1 sessão (até 2h)", "20–40 selects", "Color grade", "Exports web"],
            notIncluded: ["Deslocamento fora da zona", "Vídeo", "Impressões"],
          },
        },
      },
      photo_product: {
        id: "photo_product",
        sku: "JOM-PHOTO-PRODUCT-300",
        priceUsdt: 300,
        currency: "USDT",
        network: "TRC20",
        category: "photo",
        type: "solo",
        protocol: "PROTOCOL_05",
        badgeKey: "badge_pro",
        i18n: {
          en: {
            name: "Product Photo Pack",
            headline: "E-commerce / catalog product photography",
            description: "Clean product pack for store listings: angles, detail, lifestyle optional.",
            eta: "Scheduling + 5–8 days delivery",
            deliverables: ["Up to 8 SKUs", "3–5 angles/SKU", "Background cleanup", "Web exports"],
            notIncluded: ["Complex set construction", "Model casting"],
          },
          es: {
            name: "Pack Foto de Producto",
            headline: "Fotografía de producto e-commerce / catálogo",
            description: "Pack limpio para fichas de tienda: ángulos, detalle, lifestyle opcional.",
            eta: "Agenda + 5–8 días de entrega",
            deliverables: ["Hasta 8 SKUs", "3–5 ángulos/SKU", "Limpieza de fondo", "Exports web"],
            notIncluded: ["Set complejo", "Casting de modelos"],
          },
          fr: {
            name: "Pack Photo Produit",
            headline: "Photo produit e-commerce / catalogue",
            description: "Pack propre pour fiches boutique : angles, détail, lifestyle optionnel.",
            eta: "Planning + 5–8 jours",
            deliverables: ["Jusqu'à 8 SKUs", "3–5 angles/SKU", "Fond propre", "Exports web"],
            notIncluded: ["Set complexe", "Casting mannequins"],
          },
          pt: {
            name: "Pack Foto de Produto",
            headline: "Fotografia de produto e-commerce / catálogo",
            description: "Pack limpo para fichas de loja: ângulos, detalhe, lifestyle opcional.",
            eta: "Agenda + 5–8 dias",
            deliverables: ["Até 8 SKUs", "3–5 ângulos/SKU", "Fundo limpo", "Exports web"],
            notIncluded: ["Set complexo", "Casting de modelos"],
          },
        },
      },

      /* ───────────── UGC ───────────── */
      ugc_pack: {
        id: "ugc_pack",
        sku: "JOM-UGC-PACK-280",
        priceUsdt: 280,
        currency: "USDT",
        network: "TRC20",
        category: "ugc",
        type: "solo",
        protocol: "PROTOCOL_05",
        badgeKey: "badge_fast",
        i18n: {
          en: {
            name: "UGC Shorts Pack",
            headline: "4–6 high-retention short videos",
            description: "CapCut-driven short-form pack with hooks, captions and platform-ready exports.",
            eta: "5–8 business days",
            deliverables: ["4–6 videos (15–45s)", "Hooks + captions", "Music sync", "9:16 exports", "1 revision round"],
            notIncluded: ["Paid ad media spend", "Influencer fees"],
          },
          es: {
            name: "Pack UGC Shorts",
            headline: "4–6 videos cortos de alta retención",
            description: "Pack short-form con CapCut: hooks, captions y exports listos para plataformas.",
            eta: "5–8 días hábiles",
            deliverables: ["4–6 videos (15–45s)", "Hooks + captions", "Sync musical", "Exports 9:16", "1 ronda"],
            notIncluded: ["Presupuesto de ads", "Fees de influencers"],
          },
          fr: {
            name: "Pack UGC Shorts",
            headline: "4–6 vidéos courtes haute rétention",
            description: "Pack short-form CapCut : hooks, captions, exports plateformes.",
            eta: "5–8 jours ouvrés",
            deliverables: ["4–6 vidéos (15–45s)", "Hooks + captions", "Sync musique", "Exports 9:16", "1 round"],
            notIncluded: ["Budget ads", "Fees influenceurs"],
          },
          pt: {
            name: "Pack UGC Shorts",
            headline: "4–6 vídeos curtos de alta retenção",
            description: "Pack short-form CapCut: hooks, captions e exports prontos.",
            eta: "5–8 dias úteis",
            deliverables: ["4–6 vídeos (15–45s)", "Hooks + captions", "Sync musical", "Exports 9:16", "1 rodada"],
            notIncluded: ["Budget de ads", "Fees de influencers"],
          },
        },
      },

      /* ───────────── AUTOMATION ───────────── */
      auto_rpa: {
        id: "auto_rpa",
        sku: "JOM-AUTO-RPA-400",
        priceUsdt: 400,
        currency: "USDT",
        network: "TRC20",
        category: "automation",
        type: "solo",
        protocol: "PROTOCOL_04",
        badgeKey: "badge_pro",
        i18n: {
          en: {
            name: "RPA / Data Pipeline",
            headline: "Python automation: scrape → clean → Excel/DB",
            description: "Custom automation pipeline for catalogs, inventories or repetitive ops.",
            eta: "7–12 business days",
            deliverables: ["Script package", "Config file", "Run instructions", "Sample output", "1 revision round"],
            notIncluded: ["Illegal scraping targets", "24/7 hosting ops"],
          },
          es: {
            name: "RPA / Pipeline de Datos",
            headline: "Automatización Python: scrape → limpia → Excel/DB",
            description: "Pipeline a medida para catálogos, inventarios u ops repetitivas.",
            eta: "7–12 días hábiles",
            deliverables: ["Paquete de scripts", "Config", "Instrucciones", "Output de muestra", "1 ronda"],
            notIncluded: ["Targets ilegales", "Hosting 24/7"],
          },
          fr: {
            name: "RPA / Pipeline Data",
            headline: "Automatisation Python : scrape → clean → Excel/DB",
            description: "Pipeline sur mesure pour catalogues, inventaires, ops répétitives.",
            eta: "7–12 jours ouvrés",
            deliverables: ["Scripts", "Config", "Instructions", "Sample output", "1 round"],
            notIncluded: ["Cibles illégales", "Hosting 24/7"],
          },
          pt: {
            name: "RPA / Pipeline de Dados",
            headline: "Automação Python: scrape → limpa → Excel/DB",
            description: "Pipeline sob medida para catálogos, inventários ou ops repetitivas.",
            eta: "7–12 dias úteis",
            deliverables: ["Scripts", "Config", "Instruções", "Sample output", "1 rodada"],
            notIncluded: ["Targets ilegais", "Hosting 24/7"],
          },
        },
      },
      chrome_ext: {
        id: "chrome_ext",
        sku: "JOM-AUTO-EXT-350",
        priceUsdt: 350,
        currency: "USDT",
        network: "TRC20",
        category: "automation",
        type: "solo",
        protocol: "PROTOCOL_04",
        badgeKey: "badge_pro",
        i18n: {
          en: {
            name: "Chrome Extension (MV3)",
            headline: "Custom browser tool for your workflow",
            description: "Manifest V3 extension: popup, content script, storage — tailored to one core job.",
            eta: "8–12 business days",
            deliverables: ["MV3 codebase", "Icons + popup UI", "Install guide", "1 revision round"],
            notIncluded: ["Chrome Web Store paid listing fees", "Enterprise MDM rollout"],
          },
          es: {
            name: "Extensión Chrome (MV3)",
            headline: "Tool de navegador a medida para tu flujo",
            description: "Extensión Manifest V3: popup, content script, storage — un job core.",
            eta: "8–12 días hábiles",
            deliverables: ["Código MV3", "Iconos + UI popup", "Guía de install", "1 ronda"],
            notIncluded: ["Fees Chrome Web Store", "Rollout enterprise MDM"],
          },
          fr: {
            name: "Extension Chrome (MV3)",
            headline: "Outil navigateur sur mesure",
            description: "Extension Manifest V3 : popup, content script, storage.",
            eta: "8–12 jours ouvrés",
            deliverables: ["Code MV3", "Icônes + popup", "Guide install", "1 round"],
            notIncluded: ["Frais Chrome Web Store", "Rollout MDM"],
          },
          pt: {
            name: "Extensão Chrome (MV3)",
            headline: "Tool de navegador sob medida",
            description: "Extensão Manifest V3: popup, content script, storage.",
            eta: "8–12 dias úteis",
            deliverables: ["Código MV3", "Ícones + popup", "Guia de install", "1 rodada"],
            notIncluded: ["Fees Chrome Web Store", "Rollout MDM"],
          },
        },
      },

      /* ───────────── BUNDLES (combines related) ───────────── */
      bundle_brand_web: {
        id: "bundle_brand_web",
        sku: "JOM-BND-BRANDWEB-380",
        priceUsdt: 380,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        featured: true,
        combines: ["brand_identity", "spark"],
        i18n: {
          en: {
            name: "Brand + Web Launch",
            headline: "Identity kit + conversion landing",
            description: "Start a project the right way: brand system + Spark landing wired to WhatsApp.",
            eta: "8–12 business days",
            combines: ["Brand Identity Kit", "Micro Alchemy Spark"],
            deliverables: ["Full Brand Identity Kit", "Full Spark landing", "Brand applied on web", "2 revision rounds"],
            notIncluded: ["E-commerce", "Photo session"],
          },
          es: {
            name: "Marca + Web Launch",
            headline: "Identidad + landing de conversión",
            description: "Arranque correcto: sistema de marca + landing Spark con WhatsApp.",
            eta: "8–12 días hábiles",
            combines: ["Kit de Identidad", "Micro Alchemy Spark"],
            deliverables: ["Kit de identidad completo", "Landing Spark completa", "Marca aplicada en web", "2 rondas"],
            notIncluded: ["E-commerce", "Sesión de foto"],
          },
          fr: {
            name: "Marque + Web Launch",
            headline: "Identité + landing de conversion",
            description: "Bon départ : système de marque + landing Spark WhatsApp.",
            eta: "8–12 jours ouvrés",
            combines: ["Kit Identité", "Micro Alchemy Spark"],
            deliverables: ["Kit identité", "Landing Spark", "Marque appliquée", "2 rounds"],
            notIncluded: ["E-commerce", "Séance photo"],
          },
          pt: {
            name: "Marca + Web Launch",
            headline: "Identidade + landing de conversão",
            description: "Começo certo: sistema de marca + landing Spark com WhatsApp.",
            eta: "8–12 dias úteis",
            combines: ["Kit de Identidade", "Micro Alchemy Spark"],
            deliverables: ["Kit identidade", "Landing Spark", "Marca na web", "2 rodadas"],
            notIncluded: ["E-commerce", "Sessão de foto"],
          },
        },
      },
      bundle_brand_store: {
        id: "bundle_brand_store",
        sku: "JOM-BND-BRANDSHOP-620",
        priceUsdt: 620,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        combines: ["brand_identity", "web_ecommerce"],
        i18n: {
          en: {
            name: "Brand + Store",
            headline: "Identity + e-commerce storefront",
            description: "Brand system applied across a fast commerce front.",
            eta: "12–16 business days",
            combines: ["Brand Identity Kit", "Commerce Storefront"],
            deliverables: ["Brand kit", "Storefront", "Brand applied on product UI", "2 revision rounds"],
            notIncluded: ["Product photography", "ERP"],
          },
          es: {
            name: "Marca + Tienda",
            headline: "Identidad + storefront e-commerce",
            description: "Sistema de marca aplicado en tienda rápida.",
            eta: "12–16 días hábiles",
            combines: ["Kit de Identidad", "Tienda E-commerce"],
            deliverables: ["Kit de marca", "Storefront", "Marca en UI de producto", "2 rondas"],
            notIncluded: ["Foto de producto", "ERP"],
          },
          fr: {
            name: "Marque + Boutique",
            headline: "Identité + vitrine e-commerce",
            description: "Système de marque appliqué à une boutique rapide.",
            eta: "12–16 jours ouvrés",
            combines: ["Kit Identité", "Boutique E-commerce"],
            deliverables: ["Kit marque", "Vitrine", "Marque sur UI produit", "2 rounds"],
            notIncluded: ["Photo produit", "ERP"],
          },
          pt: {
            name: "Marca + Loja",
            headline: "Identidade + vitrine e-commerce",
            description: "Sistema de marca aplicado em loja rápida.",
            eta: "12–16 dias úteis",
            combines: ["Kit de Identidade", "Loja E-commerce"],
            deliverables: ["Kit de marca", "Vitrine", "Marca na UI", "2 rodadas"],
            notIncluded: ["Foto de produto", "ERP"],
          },
        },
      },
      bundle_game_art: {
        id: "bundle_game_art",
        sku: "JOM-BND-GAMEART-820",
        priceUsdt: 820,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        featured: true,
        combines: ["engine", "art_game"],
        i18n: {
          en: {
            name: "Game + Illustration",
            headline: "Interactive engine + game art pack",
            description: "Playable web prototype with a cohesive illustration set for characters/UI.",
            eta: "14–20 business days",
            combines: ["Interactive Engine Build", "Game Illustration Pack"],
            deliverables: ["Playable engine", "8–15 game assets", "UI integration of art", "2 revision rounds"],
            notIncluded: ["100+ card library", "Unity multiplayer"],
          },
          es: {
            name: "Juego + Ilustración",
            headline: "Motor interactivo + pack de arte",
            description: "Prototipo web jugable con set de ilustración cohesivo para personajes/UI.",
            eta: "14–20 días hábiles",
            combines: ["Motor Interactivo", "Pack Ilustración para Juegos"],
            deliverables: ["Motor jugable", "8–15 assets", "Arte integrado en UI", "2 rondas"],
            notIncluded: ["Librería 100+ cartas", "Multiplayer Unity"],
          },
          fr: {
            name: "Jeu + Illustration",
            headline: "Moteur interactif + pack art",
            description: "Prototype web jouable avec set d'illustration cohérent.",
            eta: "14–20 jours ouvrés",
            combines: ["Moteur Interactif", "Pack Illustration Jeu"],
            deliverables: ["Moteur jouable", "8–15 assets", "Art intégré UI", "2 rounds"],
            notIncluded: ["Lib 100+ cartes", "Multiplayer Unity"],
          },
          pt: {
            name: "Jogo + Ilustração",
            headline: "Motor interativo + pack de arte",
            description: "Protótipo web jogável com set de ilustração coeso.",
            eta: "14–20 dias úteis",
            combines: ["Motor Interativo", "Pack Ilustração para Jogos"],
            deliverables: ["Motor jogável", "8–15 assets", "Arte na UI", "2 rodadas"],
            notIncluded: ["Lib 100+ cartas", "Multiplayer Unity"],
          },
        },
      },
      bundle_photo_web: {
        id: "bundle_photo_web",
        sku: "JOM-BND-PHOTOWEB-380",
        priceUsdt: 380,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        combines: ["photo_session", "spark"],
        i18n: {
          en: {
            name: "Photo + Landing",
            headline: "Brand photo session + Spark landing",
            description: "Shoot selects wired into a conversion page built for your offer.",
            eta: "10–14 business days",
            combines: ["Brand Photo Session", "Micro Alchemy Spark"],
            deliverables: ["Photo session package", "Landing with your photos", "WhatsApp CTA", "2 revision rounds"],
            notIncluded: ["Paid ads", "Prints"],
          },
          es: {
            name: "Foto + Landing",
            headline: "Sesión de marca + landing Spark",
            description: "Selects de sesión integrados en landing de conversión.",
            eta: "10–14 días hábiles",
            combines: ["Sesión de Foto de Marca", "Micro Alchemy Spark"],
            deliverables: ["Paquete de sesión", "Landing con tus fotos", "CTA WhatsApp", "2 rondas"],
            notIncluded: ["Ads pagos", "Impresiones"],
          },
          fr: {
            name: "Photo + Landing",
            headline: "Séance marque + landing Spark",
            description: "Selects intégrés dans une landing de conversion.",
            eta: "10–14 jours ouvrés",
            combines: ["Séance Photo de Marque", "Micro Alchemy Spark"],
            deliverables: ["Pack séance", "Landing avec photos", "CTA WhatsApp", "2 rounds"],
            notIncluded: ["Ads payants", "Tirages"],
          },
          pt: {
            name: "Foto + Landing",
            headline: "Sessão de marca + landing Spark",
            description: "Selects integrados em landing de conversão.",
            eta: "10–14 dias úteis",
            combines: ["Sessão de Foto de Marca", "Micro Alchemy Spark"],
            deliverables: ["Pacote de sessão", "Landing com suas fotos", "CTA WhatsApp", "2 rodadas"],
            notIncluded: ["Ads pagos", "Impressões"],
          },
        },
      },
      bundle_photo_shop: {
        id: "bundle_photo_shop",
        sku: "JOM-BND-PHOTOSHOP-680",
        priceUsdt: 680,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        combines: ["photo_product", "web_ecommerce"],
        i18n: {
          en: {
            name: "Product Photo + Store",
            headline: "Catalog photography + e-commerce front",
            description: "Product images produced and mounted into a fast storefront.",
            eta: "14–18 business days",
            combines: ["Product Photo Pack", "Commerce Storefront"],
            deliverables: ["Product photo pack", "Storefront", "Images integrated", "2 revision rounds"],
            notIncluded: ["Warehouse ops", "Paid traffic"],
          },
          es: {
            name: "Foto Producto + Tienda",
            headline: "Fotografía de catálogo + storefront",
            description: "Imágenes de producto producidas y montadas en tienda rápida.",
            eta: "14–18 días hábiles",
            combines: ["Pack Foto de Producto", "Tienda E-commerce"],
            deliverables: ["Pack foto producto", "Storefront", "Imágenes integradas", "2 rondas"],
            notIncluded: ["Ops de almacén", "Tráfico pago"],
          },
          fr: {
            name: "Photo Produit + Boutique",
            headline: "Photo catalogue + vitrine e-commerce",
            description: "Images produit produites et montées dans une boutique rapide.",
            eta: "14–18 jours ouvrés",
            combines: ["Pack Photo Produit", "Boutique E-commerce"],
            deliverables: ["Pack photo", "Vitrine", "Images intégrées", "2 rounds"],
            notIncluded: ["Ops entrepôt", "Trafic payant"],
          },
          pt: {
            name: "Foto Produto + Loja",
            headline: "Foto de catálogo + vitrine e-commerce",
            description: "Imagens de produto produzidas e montadas em loja rápida.",
            eta: "14–18 dias úteis",
            combines: ["Pack Foto de Produto", "Loja E-commerce"],
            deliverables: ["Pack foto", "Vitrine", "Imagens integradas", "2 rodadas"],
            notIncluded: ["Ops de armazém", "Tráfego pago"],
          },
        },
      },
      bundle_ugc_brand: {
        id: "bundle_ugc_brand",
        sku: "JOM-BND-UGCBRAND-460",
        priceUsdt: 460,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        combines: ["ugc_pack", "brand_identity"],
        i18n: {
          en: {
            name: "UGC + Brand",
            headline: "Identity kit + short-form content pack",
            description: "Brand foundation plus 4–6 high-retention shorts aligned to the system.",
            eta: "9–13 business days",
            combines: ["Brand Identity Kit", "UGC Shorts Pack"],
            deliverables: ["Brand kit", "4–6 shorts", "Visual consistency pass", "2 revision rounds"],
            notIncluded: ["Ad spend", "Influencer talent fees"],
          },
          es: {
            name: "UGC + Marca",
            headline: "Identidad + pack de shorts",
            description: "Base de marca + 4–6 shorts de alta retención alineados al sistema.",
            eta: "9–13 días hábiles",
            combines: ["Kit de Identidad", "Pack UGC Shorts"],
            deliverables: ["Kit de marca", "4–6 shorts", "Pass de consistencia visual", "2 rondas"],
            notIncluded: ["Gasto en ads", "Fees de talent"],
          },
          fr: {
            name: "UGC + Marque",
            headline: "Identité + pack de shorts",
            description: "Base de marque + 4–6 shorts haute rétention.",
            eta: "9–13 jours ouvrés",
            combines: ["Kit Identité", "Pack UGC Shorts"],
            deliverables: ["Kit marque", "4–6 shorts", "Pass cohérence visuelle", "2 rounds"],
            notIncluded: ["Budget ads", "Fees talent"],
          },
          pt: {
            name: "UGC + Marca",
            headline: "Identidade + pack de shorts",
            description: "Base de marca + 4–6 shorts de alta retenção.",
            eta: "9–13 dias úteis",
            combines: ["Kit de Identidade", "Pack UGC Shorts"],
            deliverables: ["Kit de marca", "4–6 shorts", "Pass de consistência", "2 rodadas"],
            notIncluded: ["Gasto em ads", "Fees de talent"],
          },
        },
      },
      bundle_launch_brand: {
        id: "bundle_launch_brand",
        sku: "JOM-BND-LAUNCHBRAND-480",
        priceUsdt: 480,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_best",
        featured: true,
        combines: ["launch", "brand_identity"],
        i18n: {
          en: {
            name: "Launch Kit + Brand",
            headline: "Interactive web experience + identity",
            description: "Flagship Launch Kit styled with a fresh brand system — premium presence, ready to sell.",
            eta: "10–14 business days",
            combines: ["Digital Alchemy Launch Kit", "Brand Identity Kit"],
            deliverables: ["Launch Kit full scope", "Brand kit", "Brand applied to interactive UI", "2 revision rounds"],
            notIncluded: ["Full-stack backend", "Photo session"],
          },
          es: {
            name: "Launch Kit + Marca",
            headline: "Experiencia web interactiva + identidad",
            description: "Launch Kit insignia con sistema de marca nuevo — presencia premium lista para vender.",
            eta: "10–14 días hábiles",
            combines: ["Digital Alchemy Launch Kit", "Kit de Identidad"],
            deliverables: ["Alcance completo Launch Kit", "Kit de marca", "Marca en UI interactiva", "2 rondas"],
            notIncluded: ["Backend full-stack", "Sesión de foto"],
          },
          fr: {
            name: "Launch Kit + Marque",
            headline: "Expérience web interactive + identité",
            description: "Launch Kit phare stylé avec un nouveau système de marque.",
            eta: "10–14 jours ouvrés",
            combines: ["Digital Alchemy Launch Kit", "Kit Identité"],
            deliverables: ["Scope Launch Kit", "Kit marque", "Marque sur UI", "2 rounds"],
            notIncluded: ["Backend full-stack", "Séance photo"],
          },
          pt: {
            name: "Launch Kit + Marca",
            headline: "Experiência web interativa + identidade",
            description: "Launch Kit emblemático com sistema de marca novo.",
            eta: "10–14 dias úteis",
            combines: ["Digital Alchemy Launch Kit", "Kit de Identidade"],
            deliverables: ["Escopo Launch Kit", "Kit de marca", "Marca na UI", "2 rodadas"],
            notIncluded: ["Backend full-stack", "Sessão de foto"],
          },
        },
      },
      bundle_studio: {
        id: "bundle_studio",
        sku: "JOM-BND-STUDIO-800",
        priceUsdt: 800,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_premium",
        combines: ["brand_identity", "spark", "photo_session"],
        i18n: {
          en: {
            name: "Studio Presence Trio",
            headline: "Brand + photo + landing (full first presence)",
            description: "Everything to open digital doors: identity, directed photos, conversion landing.",
            eta: "14–18 business days",
            combines: ["Brand Identity Kit", "Brand Photo Session", "Micro Alchemy Spark"],
            deliverables: ["Brand kit", "Photo package", "Landing with photos + brand", "2 revision rounds"],
            notIncluded: ["E-commerce", "UGC video pack"],
          },
          es: {
            name: "Trío Presencia Studio",
            headline: "Marca + foto + landing (presencia completa)",
            description: "Todo para abrir puertas digitales: identidad, fotos dirigidas, landing de conversión.",
            eta: "14–18 días hábiles",
            combines: ["Kit de Identidad", "Sesión de Foto de Marca", "Micro Alchemy Spark"],
            deliverables: ["Kit de marca", "Paquete foto", "Landing con fotos + marca", "2 rondas"],
            notIncluded: ["E-commerce", "Pack UGC video"],
          },
          fr: {
            name: "Trio Présence Studio",
            headline: "Marque + photo + landing",
            description: "Tout pour ouvrir une présence digitale : identité, photos, landing.",
            eta: "14–18 jours ouvrés",
            combines: ["Kit Identité", "Séance Photo", "Micro Alchemy Spark"],
            deliverables: ["Kit marque", "Pack photo", "Landing brandée", "2 rounds"],
            notIncluded: ["E-commerce", "Pack UGC"],
          },
          pt: {
            name: "Trio Presença Studio",
            headline: "Marca + foto + landing",
            description: "Tudo para abrir presença digital: identidade, fotos, landing.",
            eta: "14–18 dias úteis",
            combines: ["Kit de Identidade", "Sessão de Foto", "Micro Alchemy Spark"],
            deliverables: ["Kit de marca", "Pacote foto", "Landing com marca", "2 rodadas"],
            notIncluded: ["E-commerce", "Pack UGC"],
          },
        },
      },
      bundle_ai_ugc: {
        id: "bundle_ai_ugc",
        sku: "JOM-BND-AIUGC-420",
        priceUsdt: 420,
        currency: "USDT",
        network: "TRC20",
        category: "bundles",
        type: "bundle",
        badgeKey: "badge_save",
        combines: ["ai_visual", "ugc_pack"],
        i18n: {
          en: {
            name: "AI Visuals + UGC",
            headline: "Art direction pack + short-form videos",
            description: "Visual system from AI pipeline feeding high-retention shorts.",
            eta: "8–12 business days",
            combines: ["AI Visual Direction Pack", "UGC Shorts Pack"],
            deliverables: ["12–20 visuals", "4–6 shorts", "Shared style notes", "2 revision rounds"],
            notIncluded: ["Ad spend", "Long-form documentary"],
          },
          es: {
            name: "Visuales IA + UGC",
            headline: "Pack de dirección visual + shorts",
            description: "Sistema visual IA alimentando shorts de alta retención.",
            eta: "8–12 días hábiles",
            combines: ["Pack Dirección Visual IA", "Pack UGC Shorts"],
            deliverables: ["12–20 visuales", "4–6 shorts", "Notas de estilo", "2 rondas"],
            notIncluded: ["Gasto en ads", "Documental long-form"],
          },
          fr: {
            name: "Visuels IA + UGC",
            headline: "Direction visuelle + shorts",
            description: "Système visuel IA alimentant des shorts haute rétention.",
            eta: "8–12 jours ouvrés",
            combines: ["Pack Direction Visuelle IA", "Pack UGC Shorts"],
            deliverables: ["12–20 visuels", "4–6 shorts", "Notes de style", "2 rounds"],
            notIncluded: ["Budget ads", "Long format"],
          },
          pt: {
            name: "Visuais IA + UGC",
            headline: "Direção visual + shorts",
            description: "Sistema visual IA alimentando shorts de alta retenção.",
            eta: "8–12 dias úteis",
            combines: ["Pack Direção Visual IA", "Pack UGC Shorts"],
            deliverables: ["12–20 visuais", "4–6 shorts", "Notas de estilo", "2 rodadas"],
            notIncluded: ["Gasto em ads", "Long-form"],
          },
        },
      },

      custom: {
        id: "custom",
        sku: "JOM-CUSTOM-QUOTE",
        priceUsdt: 0,
        currency: "USDT",
        network: "TRC20",
        category: "web",
        type: "solo",
        badgeKey: "badge_quote",
        i18n: {
          en: {
            name: "Strategic Custom Build",
            headline: "Scoped quote in 24h",
            description: "Custom brief across full-stack, RPA, brand, UGC or hybrid scopes.",
            eta: "Depends on scope",
            deliverables: ["Discovery", "USDT proposal with milestones", "Kickoff 48h post-payment"],
            notIncluded: [],
          },
          es: {
            name: "Proyecto Custom Estratégico",
            headline: "Cotización en 24h",
            description: "Brief a medida: full-stack, RPA, marca, UGC o híbridos.",
            eta: "Según alcance",
            deliverables: ["Discovery", "Propuesta USDT con hitos", "Kickoff 48h post-pago"],
            notIncluded: [],
          },
          fr: {
            name: "Build Custom Stratégique",
            headline: "Devis sous 24h",
            description: "Brief sur mesure : full-stack, RPA, marque, UGC ou hybride.",
            eta: "Selon le scope",
            deliverables: ["Discovery", "Proposition USDT", "Kickoff 48h post-paiement"],
            notIncluded: [],
          },
          pt: {
            name: "Build Custom Estratégico",
            headline: "Orçamento em 24h",
            description: "Brief sob medida: full-stack, RPA, marca, UGC ou híbrido.",
            eta: "Conforme escopo",
            deliverables: ["Discovery", "Proposta USDT", "Kickoff 48h pós-pagamento"],
            notIncluded: [],
          },
        },
      },
    },

    defaultProductId: "launch",

    admin: {
      password: "jom2026",
      storageKeys: {
        orders: "jom_orders_v1",
        briefs: "jom_contact_briefs",
        events: "jom_ops_events_v1",
      },
    },

    messages: {
      orderWaTemplate: function (order) {
        return (
          `🚀 *NUEVO PEDIDO JOM STUDIO*%0A` +
          `────────────────%0A` +
          `*Orden:* ${order.id}%0A` +
          `*Producto:* ${order.productName}%0A` +
          `*Monto:* ${order.amount} USDT (${order.network})%0A` +
          `*Cliente:* ${encodeURIComponent(order.name)}%0A` +
          `*Email:* ${encodeURIComponent(order.email)}%0A` +
          `*Brief:* ${encodeURIComponent(order.brief || "—")}%0A` +
          `*Tx Hash:* ${order.txHash || "pendiente"}%0A` +
          `*Estado:* ${order.status}%0A` +
          `*Fecha:* ${encodeURIComponent(order.createdAt)}`
        );
      },
      clientPaidWa: function (order) {
        return (
          `Hola JOM STUDIO 👋%0A` +
          `Acabo de pagar el *${encodeURIComponent(order.productName)}* (%20${order.amount}%20USDT%20TRC20).%0A` +
          `Orden:%20${order.id}%0A` +
          `Hash:%20${order.txHash || "adjunto captura"}%0A` +
          `Email:%20${encodeURIComponent(order.email)}%0A` +
          `Listo para kickoff.`
        );
      },
    },
  };

  global.JOM_CONFIG = CONFIG;
})(typeof window !== "undefined" ? window : globalThis);
